server:
  port: 8098

spring:
    mvc:
        view:
            prefix: /WEB-INF/
            suffix: .jsp
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/mybatisprac
        username: root
        password: root
    security:
      oauth2:
        client:
          registration:
            # Google OAuth2
            google:
              client-id: 887576412728-ncmn325tihirmorg9lv2m79fi6jvu92b.apps.googleusercontent.com
              client-secret: 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
              scope:
                - email
                - profile
            
            # # Kakao OAuth2
            # kakao:
            #   client-id: YOUR_KAKAO_CLIENT_ID
            #   client-secret: YOUR_KAKAO_CLIENT_SECRET
            #   client-authentication-method: client_secret_post
            #   authorization-grant-type: authorization_code
            #   redirect-uri: "{baseUrl}/oauth2/callback/kakao"
            #   scope:
            #     - profile_nickname
            #     - account_email
            #   client-name: Kakao
            
            # # Naver OAuth2
            # naver:
            #   client-id: YOUR_NAVER_CLIENT_ID
            #   client-secret: YOUR_NAVER_CLIENT_SECRET
            #   client-authentication-method: client_secret_post
            #   authorization-grant-type: authorization_code
            #   redirect-uri: "{baseUrl}/oauth2/callback/naver"
            #   scope:
            #     - name
            #     - email
            #   client-name: Naver

        # provider:
        #   kakao:
        #     authorization-uri: https://kauth.kakao.com/oauth/authorize
        #     token-uri: https://kauth.kakao.com/oauth/token
        #     user-info-uri: https://kapi.kakao.com/v2/user/me
        #     user-name-attribute: id
          
        #   naver:
        #     authorization-uri: https://nid.naver.com/oauth2.0/authorize
        #     token-uri: https://nid.naver.com/oauth2.0/token
        #     user-info-uri: https://openapi.naver.com/v1/nid/me
        #     user-name-attribute: response

mybatis:
  type-aliases-package: com.example.base.domain


# JWT 설정
jwt:
  secret: SDFKLSDJLFKJ3LSKDFJKLB9SDFLKJ33KNVLKSDFJ39048SDLKFNBNLSKDRJ405920AKLDSJ34
  access-token-expiration: 3600000  # 1시간 (밀리초)
  refresh-token-expiration: 604800000  # 7일 (밀리초)

#JWT 토큰을 받을 최종 페이지
# app:
#   oauth2:
#     redirect-uri: http://localhost:8098/oauth2/redirect